<?php

function Users_activate_post()
{
	Q_Valid::nonce(true);
	
	/**
	 * @var Users_User $user
	*/
	$email = $mobile = $type = $user = null;
	$sessionFresh = false; // whether this request already issued a new session id
	extract(Users::$cache, EXTR_IF_EXISTS);
	
	$text = Q_Text::get('Users/content');

	if (isset($_REQUEST['passphrase'])) {
		if (empty($_REQUEST['passphrase'])) {
			throw new Q_Exception("You can't set a blank passphrase.", 'passphrase');
		}
		
		$isHashed = !empty($_REQUEST['isHashed']);
		if ($isHashed and $isHashed !== 'true' and intval($_REQUEST['isHashed']) > 1) {
			// this will let us introduce other values for isHashed in the future
			throw new Q_Exception("Please set isHashed to 0 or 1", 'isHashed');
		}

		// Save the pass phrase even if there may be a problem adding an email later.
		// At least the user will be able to log in.
		$passphrase = $user->preparePassphrase($_REQUEST['passphrase'], $isHashed);
		// hashPassphrase()'s second parameter is the ALGORITHM (default
		// 'password_hash'). This used to pass the existing hash there, which
		// only worked because no hash equals 'hash_pbkdf2' (ro#579).
		$user->passphraseHash = $user->hashPassphrase($passphrase);
		Q_Response::setNotice("Users/activate/passphrase",  $text['notifications']['PassphraseSaved'], array(
			'timeout' => Q_Config::get('Users', 'notices', 'timeout', 5)
		));
		// Log the user in, since they were able to set the passphrase
		// setLoggedInUser() returns false, without regenerating the session id
		// or saving, when this user is already logged in (ro#548, audit R04).
		if (Users::setLoggedInUser($user) === false) {
			$user->save();
		} else {
			$sessionFresh = true;
		}

		if (empty($user->passphraseHash)) {
			throw new Q_Exception("Please set a pass phrase on your account", 'passphrase', true);
		}

		// Changing the passphrase has to end every other session, not just
		// prove the new one works. Setting the hash alone left a cookie
		// copied from a lost phone, a shared laptop or a backup valid for the
		// rest of the session lifetime - which is the exact situation someone
		// is trying to get out of when they reset their password. The current
		// session (already regenerated by setLoggedInUser above) is kept, so
		// the user isn't logged out of the tab they just used. See ro#546.
		if (Q_Config::get('Users', 'session', 'invalidateOthersOnPassphraseChange', true)) {
			if (!$sessionFresh) {
				Users::rotateSession($user);
				$sessionFresh = true;
			}
			Users::logoutOtherSessions($user, Q_Session::id());
		}
	}

	if ($type) {
		// What the account was reachable by before this call. Read it first:
		// setEmailAddress() / setMobileNumber() overwrite the user's field.
		$previousEmail = $user->emailAddress;
		$previousMobile = $user->mobileNumber;
		if ($type == 'email address') {
			$user->setEmailAddress($email->address, true); // may throw exception
			$activatedValue = $email->address;
		} else if ($type == 'mobile number') {
			$user->setMobileNumber($mobile->number, true); // may throw exception
			$activatedValue = $mobile->number;
		}
		// null for the account's first identifier, else "added" or "replaced"
		// (ro#548, Opus audit R02: registration is per account, not per field).
		$kind = Users::identifierChangeKind($type, $activatedValue, $previousEmail, $previousMobile);
		// Log the user in, since they have just added an email to their account
		$activated = Q::interpolate($text['notifications']['IdentifierActivated'], @compact('type'));
		if (Users::setLoggedInUser($user) !== false) {
			$sessionFresh = true;
		}

		// Changing a login identifier is a credential event: the identifier is
		// what Users/login matches on and what recovery is sent to, so whoever
		// controls it controls the account. An attacker holding only a session
		// could otherwise swap or add one and keep their foothold. Only the
		// account's very first identifier (registration) has nothing to
		// protect. See ro#548.
		if ($kind) {
			// Rotate too when this request did not: an already-logged-in
			// browser keeps its id through setLoggedInUser (audit R04).
			Users::identifierCredentialEvent(
				$user, $type, $previousEmail, !$sessionFresh, $previousMobile, $kind
			);
		}
		Q_Response::removeNotice('Users/activate/objects');
		Q_Response::setNotice("Users/activate/activated", $activated, array(
			'timeout' => Q_Config::get('Users', 'notices', 'timeout', 5)
		));
	}

	if ($user) {
		Q_Response::setSlot('user', $user->exportArray());
	}
	Q_Response::setSlot('form', '');
	
	Users::$cache['passphrase_set'] = true;
	Users::$cache['success'] = true;
}
